### ISSUE TITLE
What is size0 in helper.py?

### ISSUE THREAD

**Issue by mkumar10** [TAMU-VITA/GLNet#5]
Seems to be required for `mode=3` but is not defined in the train file?

**Comment by lamhoangtung** [comment]
> Seems to be required for `mode=3` but is not defined in the train file?

I facing the same question when trying mode 3, do you find the meaning of `size0` when init `Trainer` object yet ?

https://github.com/chenwydj/ultra_high_resolution_segmentation/blob/e3ad351d2291ec03b6108dd17b9be57fa89ba4ed/helper.py#L282-L283

**Comment by lamhoangtung** [comment]
@chenwydj I'm digging through the git history and find that before you have set `size0` in this commit

https://github.com/lamhoangtung/ultra_high_resolution_segmentation/blob/50fb97525ca070c302063fca86b000624058e2ee/train_deep_globe.py#L67-L75

Can you explain a bit why does this being set to `(2448, 2448)` ?  Seem like this is the maximum image size of the DeepGlobe dataset ....

But if this true, does it require to be a square ?

**Comment by lamhoangtung** [comment]
@mkumar10 `size0` help construct the template for prediction. The author may forgot to push the newest code and left the `size0` there (since DeepGlobe have the same size so temple size will be exactly the same for every sample). I tried to fix this in 36b1deda80ee7c6c37ba88d46f26b3b01dd45f6f, e3c51283c575ae92481210eb072b3109ce7f523b and fa3a46c28f8aa160b6ba42fbfd7f1c8c836e5aad. Take a look ;)

**Comment by chenwydj** [comment]
You are right: size0 stands for the size of the original global image. For the Deep Globe the image size is HxW = 2448x2448. I just update the helper.py.
